apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-spion-frontend
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 443
  liveness:
    path: isalive
    initialDelay: 15
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 15
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  ingresses:
    - https://helse-spion-frontend.nais.preprod.local
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 256Mi
  env:
  - name: APP_URL_SPION
    value: http://helse-spion
