apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-spion-frontend
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://arbeidsgiver-min-side-refusjon.dev.nav.no
  liveness:
    path: /health/is-alive
    initialDelay: 15
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: /health/is-ready
    initialDelay: 15
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 256Mi
