apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-spion-frontend
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 3000
  liveness:
    path: isalive
    initialDelay: 15
    timeout: 3
    periodSeconds: 3
    failureThreshold: 10
    port: 3000
  readiness:
    path: isready
    initialDelay: 15
    timeout: 3
    periodSeconds: 3
    failureThreshold: 10
    port: 3000
  ingresses:
    - https://helse-spion-frontend.nais.adeo.no
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 64Mi
