name: Test

on:
  pull_request:
    branches:
      - main
    branches-ignore:
      - dependabot/*
      - snyk-*

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
      - run: yarn test
